### ISSUE TITLE
Weekly Meeting for December 2, 2024

### ISSUE THREAD

**Issue by Blargie** [Blargie/SYSC4806Project#30]
Answer the following questions:
- What have I done this week?
- What will I do next week?
- What is holding me back?

**Comment by Keegan9049** [comment]
What have I done this week?
Fixed issues  from the numericRange Awnsers
What will I do next week?
Implement new slider question type
What is holding me back?
Other course work

**Comment by MohannadDukhan** [comment]
What have I done this week?
Worked on generate report, added pie chart and histogram answers
What will I do next week?
What is holding me back?
Final exams
